### ISSUE TITLE
emacs?

### ISSUE THREAD

**Issue by tmcw** [rapidsms/rapidsms-documentation#9]
The ubuntu_install.rst documentation recommends installing emacs? Why? This is kind of a bizarre call-out, and I don't think it's anywhere near the scope of webapp documentation.

And I'm not just posting this because I <3 VIM.

**Comment by holagvk** [comment]
Installing emacs is just redundant for this case. I think no one is maintaining the documentation right now, otherwise the issue would have been closed now! ...
